add link color var and <li> link style
markoco14/cfiw pull request #3
Opened 2021-07-17 02:02 UTC by markoco14

2021-07-18 19:18 UTC, Strangehill requested changes
We can totally ship this, but i'm sending it back with the "Request changes" option selected just for the fun of it.

2021-07-18 19:18 UTC, Strangehill commented on css/style.css
> +/*i added this because <li> links weren't taking on the color
- yes. that sounds about right. 
- best to remove this comment from the file

2021-07-18 19:18 UTC, Strangehill commented on css/style.css
> +	--header-text:rgb(245,245,245);
since the rename implies this variable is for use in the header, I'd consider moving the variable to the headerStyle file as well.

2021-07-18 19:18 UTC, Strangehill commented on css/faq-style.css
> +div .faq-question:hover {
Combining one fewer selector, in this case removing the initial 'div' selector, is both cleaner and a safer habit in that it doesn't affect the declaration's specificity.

2021-07-19 06:05 UTC, markoco14 commented on css/style.css
> +	--header-text:rgb(245,245,245);
Ok, perhaps I should rename it though. That color just refers to a slightly off-white color. So far, it's only used in the header section, but there's no reason why we couldn't have white text elsewhere in the project. 

We can decide if it should be reserved only for the header/nav bar or if we should be able to use that color in other parts of the site (for example, if a box had a dark background, that color could be called to make the text white).

=>Move or rename? ie --light-text:rgb(245,245,245); or --white-text:rgb(245,245,245);

2021-07-19 06:06 UTC, markoco14 commented on css/faq-style.css
> +div .faq-question:hover {
I'll take another look at it, but I think the style wasn't applying to the .faq-question class without the div tag. This might have something to do with some other .innerHTML questions I have for you.

2021-07-19 06:07 UTC, markoco14 commented on css/faq-style.css
> +div .faq-question:hover {
the short story is: do you think the questions on the faq page should be heading elements (<h2,3,4,5,6>), and therefore naturally bolded and different from the answer text; or <p> elements with font-weight: bold?

2021-07-19 06:11 UTC, Strangehill commented on css/style.css
> +	--header-text:rgb(245,245,245);
Rename back to something color related

2021-07-19 06:13 UTC, Strangehill commented on css/faq-style.css
> +div .faq-question:hover {
It sounds like a good use case for definition lists.

2021-07-19 06:14 UTC, Strangehill commented on css/faq-style.css
> +div .faq-question:hover {
I think it goes dl>(dt+dd)

2021-07-19 08:51 UTC, merged